from django.template import Template

schema_template = Template("""# @generated
# AUTO-GENERATED BY WAGTAIL-NINJA
# DO NOT EDIT THIS FILE DIRECTLY

from typing import Literal

from ninja import ModelSchema
from pydantic import Field
from wagtail_ninja.schema import BasePageDetailSchema

{% for imprt in imports %}
{{ imprt|safe }}
{% endfor %}

{% for model in models %}
class {{ model.name }}Schema(BasePageDetailSchema, ModelSchema):
    content_type: Literal["{{app_label}}.{{ model.name }}"]
    {% for annotation in model.annotations %}
    {{ annotation|safe }}{% endfor %}

    class Meta:
        model = "{{ app_label }}.{{ model.name }}"
        fields = [{% for field in model.fields %}
            "{{ field }}",{% endfor %}
        ]

    {% for resolver in model.resolvers %}
    {{ resolver|safe }}
    {% endfor %}

{% endfor %}""")


api_template = Template("""# @generated
# AUTO-GENERATED BY WAGTAIL-NINJA
# DO NOT EDIT THIS FILE DIRECTLY

from typing import Annotated

from ninja import Router
from pydantic import Field
from wagtail_ninja.router import (
    find_page,
    find_redirect,
    get_page_preview,
    get_redirect,
    list_pages,
    list_redirects,
)
from wagtail_ninja.schema import (
    BasePageDetailSchema,
    BasePageModelSchema,
    Http404Response,
    RedirectSchema,
)

from django.http import HttpRequest
from django.shortcuts import get_object_or_404
from django.utils import translation
from wagtail.models import Page


{% for app in api_apps %}
from {{ app.name }}.models import {% for pair in app.pairs %}{{ pair.model }}{% if not forloop.last %}, {% endif %}{% endfor %}
from {{ app.name }}.generated_schemas import {% for pair in app.pairs %}{{ pair.schema }}{% if not forloop.last %}, {% endif %}{% endfor %}
{% endfor %}

type WagtailPages = Annotated[
    BasePageDetailSchema
    {% for app in api_apps %}{% for pair in app.pairs %}| {{ pair.schema }}
    {% endfor %}{% endfor %},
    Field(discriminator='content_type')
]

SCHEMA_MAP = {
    {% for app in api_apps %}{% for pair in app.pairs %}{{ pair.model }}: {{ pair.schema }},
    {% endfor %}{% endfor %}
}

def _get_page(request: HttpRequest, page_id: int) -> WagtailPages:
    page = get_object_or_404(Page, id=page_id).specific

    if schema_class := SCHEMA_MAP.get(type(page)):
        return schema_class.from_orm(page, context={"request": request})

    return BasePageDetailSchema.from_orm(page, context={"request": request})


def get_page(
    request: HttpRequest, page_id: int, locale: str | None = None
) -> WagtailPages:
    if locale:
        with translation.override(locale):
            return _get_page(request, page_id)
    return _get_page(request, page_id)


class WagtailNinjaPagesRouter(Router):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.add_api_operation(
            "/", ["GET"], list_pages, response=list[BasePageModelSchema]
        )
        self.add_api_operation(
            "/find/",
            ["GET"],
            find_page,
            response={301: None, 302: None, 404: Http404Response},
        )
        self.add_api_operation(
            "/preview/", ["GET"], get_page_preview, response=WagtailPages
        )
        self.add_api_operation("/{page_id}/", ["GET"], get_page, response=WagtailPages)


class WagtailNinjaRedirectsRouter(Router):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.add_api_operation(
            "/", ["GET"], list_redirects, response=list[RedirectSchema]
        )
        self.add_api_operation(
            "/find/", ["GET"], find_redirect, response=RedirectSchema
        )
        self.add_api_operation(
            "/{redirect_id}/", ["GET"], get_redirect, response=RedirectSchema
        )

""")
